/**
 * constant.js
 */
"use strict";
{
  /* shared constants */
  module.exports = {
    CONTENT_GET: "getContent",
    CONTEXT_MENU: "contextMenu",
    CONTEXT_MODE: "contextMode",
    EDITOR_CMD_ARGS: "editorCmdArgs",
    EDITOR_CONFIG: "editorConfigPath",
    EDITOR_CONFIG_FILE: "editorconfig.json",
    EDITOR_CONFIG_GET: "getEditorConfig",
    EDITOR_CONFIG_RES: "resEditorConfig",
    EDITOR_CONFIG_SET: "setEditorConfig",
    EDITOR_CONFIG_TS: "editorConfigTimestamp",
    EDITOR_FILE_NAME: "editorFileName",
    EDITOR_FILE_POS: "editorFileAfterCmdArgs",
    EDITOR_LABEL: "editorLabel",
    EDITOR_PATH: "editorPath",
    EXT_CHROME_ID: "chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/",
    EXT_WEB_ID: "jid1-WiAigu4HIo0Tag@jetpack",
    FILE_EXT: "fileExt",
    IS_ENABLED: "isEnabled",
    KEY_ACCESS: "accessKey",
    KEY_EDITOR: "editorShortCut",
    KEY_OPTIONS: "optionsShortCut",
    HOST: "withexeditorhost",
    HOST_DESC: "Native messaging host for withExEditor",
    LABEL: "withExEditor",
    LOCAL_FILE_VIEW: "viewLocalFile",
    MODE_EDIT: "modeEditText",
    MODE_MATHML: "modeViewMathML",
    MODE_SELECTION: "modeViewSelection",
    MODE_SOURCE: "modeViewSource",
    MODE_SVG: "modeViewSVG",
    ONLY_EDITABLE: "enableOnlyEditable",
    OPTIONS_OPEN: "openOptions",
    PROCESS_CHILD: "childProcess",
    STORAGE_SET: "setStorage",
    TEXT_SYNC: "syncText",
    TMP_FILES: "tmpFiles",
    TMP_FILES_PB: "tmpFilesPb",
    TMP_FILES_PB_REMOVE: "removePrivateTmpFiles",
    TMP_FILE_CREATE: "createTmpFile",
    TMP_FILE_DATA_PORT: "portTmpFileData",
    TMP_FILE_GET: "getTmpFile",
    TMP_FILE_RES: "resTmpFile",
    VARS_SET: "setVars",
  };
}
