name: deploy

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: deploy release assets
    strategy:
      matrix:
        include:
          - node-version: 20.x
            os: ubuntu-latest
            asset-name: linux-x86_64.tar.gz
            bin-file: ./pkg/index
            make-args: --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
            zip-cmd: cd ./pkg/linux && tar -cvzf linux-x86_64.tar.gz LICENSE README.md README.ja.md index && cd ../../
            zip-mime: application/gzip
          - node-version: 20.x
            os: macos-latest
            asset-name: macos.tar.gz
            bin-file: ./pkg/index
            make-args: --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
            zip-cmd: cd ./pkg/macos && tar -cvzf macos.tar.gz LICENSE README.md README.ja.md index && cd ../../
            zip-mime: application/gzip
          - node-version: 20.x
            os: windows-latest
            asset-name: win64.zip
            bin-file: ./pkg/index.exe
            make-args: --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
            zip-cmd: npm run zip-jszip -- -o ./pkg/win/win64.zip ./pkg/win/LICENSE ./pkg/win/README.md ./pkg/win/README.ja.md ./pkg/win/index.exe
            zip-mime: application/zip
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install
      - name: prepare build
        run: npm run prebuild
      - name: make directories
        run: mkdir -p ./{bundle,pkg}
      - name: build binary
        run: |
          npm run bundle-js
          node --experimental-sea-config ./sea-config.json
          cp $(command -v node) ${{ matrix.bin-file }}
          npx postject ${{ matrix.bin-file }} NODE_JS_CODE ./pkg/index.blob ${{ matrix.make-args }}
      - name: verify binary
        run: stat ${{ matrix.bin-file }}
      - name: zip package
        run: |
          cp ./LICENSE ./README.md ./README.ja.md ./pkg
          ${{ matrix.zip-cmd }}
          stat ./pkg/${{ matrix.asset-name }}
      - name: upload release asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pkg/${{ matrix.asset-name }}
          asset_name: ${{ matrix.asset-name }}
          asset_content_type: ${{ matrix.zip-mime }}
