name: deploy

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: deploy binaries
    strategy:
      matrix:
        include:
          - node-version: 14.x
            os: ubuntu-latest
            make-args: --make-args="-j4"
            pkg-dir: ./pkg/linux
            target: ./pkg/linux/index
            zip-cmd: cd ./pkg/linux && tar -cvzf linux-x86_64.tar.gz LICENSE README.md README.ja.md index && tar -tv linux-x86_64.tar.gz && cd ../../
            zip-file: linux-x86_64.tar.gz
            zip-mime: application/gzip
          - node-version: 14.x
            os: macos-latest
            make-args: --make-args="-j4"
            pkg-dir: ./pkg/macos
            target: ./pkg/macos/index
            zip-cmd: cd ./pkg/macos && tar -cvzf macos.tar.gz LICENSE README.md README.ja.md index && tar -tv macos.tar.gz && cd ../../
            zip-file: macos.tar.gz
            zip-mime: application/gzip
          - node-version: 14.x
            os: windows-latest
            make-args: ''
            pkg-dir: ./pkg/win
            target: index.exe
            zip-cmd: npm run zippkg:win && zipinfo ./pkg/win/win64.zip
            zip-file: win64.zip
            zip-mime: application/zip
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: set up NASM
        uses: ilammy/setup-nasm@v1
      - name: install dependencies
        run: npm install
      - name: run tests
        run: |
          npm run lint
          npm test
      - name: build binary
        run: |
          mkdir -p ./{bundle,pkg/{linux,macos,win}}
          npm run bundle:js
          npm run bundle:bin -- -t ${{ matrix.target }} ${{ matrix.make-args }}
      - name: zip package
        run: |
          chmod 755 ${{ matrix.target }}
          cp ./LICENSE ./README.md ./README.ja.md ${{ matrix.pkg-dir }}
          ${{ matrix.zip-cmd }}
      - name: upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.pkg-dir}}/${{ matrix.zip-file }}
          asset_name: ${{ matrix.zip-file }}
          asset_content_type: ${{ matrix.zip-mime }}
